apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sambaai-data-pvc
  namespace: sambaai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sambaai-logs-pvc
  namespace: sambaai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi 